### ISSUE TITLE
Cross-References and Links in the Documentation are different between local and readthedocs builds

### ISSUE THREAD

**Issue by michaelweinold** [brightway-lca/brightway-documentation#104] opened 2023-07-25 07:36 UTC
@tngTUDOR will describe his woes below 🙈

**Comment by tngTUDOR** [comment] 2023-07-26 16:21
After trying some different strategies (.. and ../.. relative URLs) I can see that the problem is in the "templates":
They end up nested, so sometimes, .. will work, and some other times a ../../../ might even be necessary.

The templates are pure html, so we either hard-code (back, I know 🫣 ) or find a way to make the templates (diataxis bar and footer for example) rst or md

**Comment by tngTUDOR** [comment] 2023-07-27 10:38
jinja templating is available at html templates, we could use that to conditionally render URLs differentiating local from readthedocs builds

**Comment by tngTUDOR** [comment] 2023-07-27 11:10
per the info at [https://docs.readthedocs.io/en/stable/reference/environment-variables.html](readthedocs documentation) we can use environment variables at runtime to build the urls for the problematic template parts (diataxis table and contributing in footer)

**Comment by tngTUDOR** [comment] 2023-07-28 04:18
This was fixed by conditionally building the urls of the _templates/footer + diataxis sidebar files using jinja templating and some environment variables (to identify the kind of build, local or readthedocs)

**Comment by michaelweinold** [comment] 2023-07-28 07:04
I'll need to document this in the 'contributing' section (otherwise I'll surely forget 🙈).

**Comment by michaelweinold** [comment] 2023-07-28 14:55
I am happy to report that the two [Sphinx templating directrives](https://www.sphinx-doc.org/en/master/development/templating.html):

```
href="{{ version }}/{{ pathto('../content/contributing/contributing.html', 1) }}"
```

works both locally and on readthedocs, meaning we can replace the if-else workaround of @tngTUDOR:

```
{% if read_the_docs_build %}
href="/{{language}}/{{read_the_docs_version}}/content/contributing/contributing.html>Please report it!"
{% else %}
href="/content/contributing/contributing.html'>Please report it!"
{% endif %}
```

**Closed** 2023-07-28 14:57 UTC
Labels: documentation, enhancement
